version: '3'
services:
  zookeeper:
    image: artifactory.algol60.net/docker.io/confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: artifactory.algol60.net/docker.io/confluentinc/cp-kafka:6.1.1
    ports:
      - "29092"
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISE_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: LISTENER_INSIDE://kafka:29092,LISTENER_OUTSIDE://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INSIDE://kafka:29092,LISTENER_OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INSIDE:PLAINTEXT,LISTENER_OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  worker:
    build:
      context: .
      dockerfile: Dockerfile.testing
      network: host
    hostname: worker
    environment:
      - LOG_LEVEL=TRACE
      - BROKER_SPEC=kafka:29092
    depends_on:
      - kafka
  integration:
    image: artifactory.algol60.net/csm-docker/unstable/hms-trs-app-api-testapp:2.1.0-20220728160543.b2f7f23
    hostname: integration
    environment:
      - LOG_LEVEL=TRACE
      - BROKER_SPEC=kafka:29092
      - IMPLEMENTATION=LOCAL
    depends_on:
      - worker
